blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/AymanYehia23/ekb-toolkit/discussions
    about: Ask questions, propose ideas, and discuss the toolkit with the community.
